
import Navbar from "@/components/UI/Navbar";
import "./globals.css";
import Footer from "@/components/UI/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-full overflow-x-hidden relative bg-gray-100`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
