

const MONGO_URL=process.env.MONGO_URL
const BASE_URL= process.env.BASE_URL

const CLOUDINARY_NAME=process.env.CLOUDINARY_NAME
const CLOUDINARY_API=process.env.CLOUDINARY_API
const CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET

const JWT_SECRET=process.env.JWT_SECRET
const NODE_ENV=process.env.NODE_ENV

module.exports={
    MONGO_URL, BASE_URL, CLOUDINARY_API, CLOUDINARY_NAME, CLOUDINARY_API_SECRET, JWT_SECRET, NODE_ENV
}

